# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "branch-msbd-app"
client_id = "2377268e6e57bb7ea9b46fadf7b51563"
application_url = "https://branch-msbd-app-cee2a8728d5a.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://branch-msbd-app-cee2a8728d5a.herokuapp.com/auth/callback",
  "https://branch-msbd-app-cee2a8728d5a.herokuapp.com/auth/shopify/callback",
  "https://branch-msbd-app-cee2a8728d5a.herokuapp.com/api/auth/callback",
  "https://branch-msbd-app-cee2a8728d5a.herokuapp.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "anthony-branch-dev-store-2022.myshopify.com"
